---
title: "Replication 1"
author: "Keeley MacAfee"
date: "2/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Zelig)
library("ZeligChoice")
library(xtable)		
library(reshape)
library(apsrtable)
library(stargazer)
library(rms)
library(knitr)
library(kableExtra)
library(tidyverse)

cl   <- function(dat,fm, cluster){
           require(sandwich, quietly = TRUE)
           require(lmtest, quietly = TRUE)
           M <- length(unique(cluster))
           N <- length(cluster)
           K <- fm$rank
           dfc <- (M/(M-1))*((N-1)/(N-K))
           uj  <- apply(estfun(fm),2, function(x) tapply(x, cluster, sum));
           vcovCL <- dfc*sandwich(fm, meat=crossprod(uj)/N)
           coeftest(fm, vcovCL) }
```

```{r, message = FALSE, echo = FALSE}
### DATA ENTRY AND MANIPULATION (from replication code)####

# ## Gender cases only
 women.cases <- read.csv("glynn_sen_daughters_by_case_1.csv", stringsAsFactors = FALSE) 

# ## Removing male plaintiffs:
 women.cases <- subset(women.cases, femplaintiff == 1)

 women.cases <- subset(women.cases, area == "employment" | area == "Title IX" | area == "pregnancy" | area == "abortion" | area == "reproductive rights")

 women.cases$area <- factor(women.cases$area, levels = c("abortion","employment","pregnancy","reproductive rights","Title IX"))

# ## All cases, including non-gender cases (from Ashlyn Kuersten/Susan Haire's coding)
# cases <- read.csv("cases.for.analysis.csv")	

judge.means <- read.csv("glynn_sen_daughters_by_judge.csv", stringsAsFactors = FALSE)

all <- subset(judge.means, girls != "NaN") 
# subsets judge
								  # data to those for 
								  # whom we have fertility data
```


```{r, echo = FALSE}
########################################################
## Table 2: Judge Demographics
########################################################

dems <- subset(all, republican == 0)
reps <- subset(all, republican == 1)
women <- subset(all, woman == 1)
men <- subset(all, woman == 0)


mean.kids <-  cbind(mean(na.omit(all$child)), 
		mean(na.omit(dems$child)),
		mean(na.omit(reps$child)),
		mean(na.omit(women$child)),
		mean(na.omit(men$child))
	)

mean.girls <- cbind(mean(na.omit(all$girls)), 
		mean(na.omit(dems$girls)),
		mean(na.omit(reps$girls)),
		mean(na.omit(women$girls)),
		mean(na.omit(men$girls))
	)

prop.zero <- cbind(prop.table(table(na.omit(all$child)))[1],
prop.table(table(na.omit(dems$child)))[1],
prop.table(table(na.omit(reps$child)))[1],
prop.table(table(na.omit(women$child)))[1],
prop.table(table(na.omit(men$child)))[1]
	)
	
	
prop.one <- cbind(prop.table(table(na.omit(all$child)))[2],
prop.table(table(na.omit(dems$child)))[2],
prop.table(table(na.omit(reps$child)))[2],
prop.table(table(na.omit(women$child)))[2],
prop.table(table(na.omit(men$child)))[2]
	)
	
prop.two <- cbind(prop.table(table(na.omit(all$child)))[3],
prop.table(table(na.omit(dems$child)))[3],
prop.table(table(na.omit(reps$child)))[3],
prop.table(table(na.omit(women$child)))[3],
prop.table(table(na.omit(men$child)))[3]
	)

prop.three <- cbind(prop.table(table(na.omit(all$child)))[4],
prop.table(table(na.omit(dems$child)))[4],
prop.table(table(na.omit(reps$child)))[4],
prop.table(table(na.omit(women$child)))[4],
prop.table(table(na.omit(men$child)))[4]
	)

prop.four <- cbind(prop.table(table(na.omit(all$child)))[5],
prop.table(table(na.omit(dems$child)))[5],
prop.table(table(na.omit(reps$child)))[5],
prop.table(table(na.omit(women$child)))[5],
prop.table(table(na.omit(men$child)))[5]
	)

prop.five <- cbind(prop.table(table(na.omit(all$child)))[6],
prop.table(table(na.omit(dems$child)))[6],
prop.table(table(na.omit(reps$child)))[6],
prop.table(table(na.omit(women$child)))[6],
prop.table(table(na.omit(men$child)))[6]
	)
	
aa <- table(na.omit(all$child))
	plus6.all <- sum(aa[7:length(aa)])/sum(aa)
	
bb <- table(na.omit(dems$child))
	plus6.dems <- sum(bb[7:length(bb)])/sum(bb)

cc <- table(na.omit(reps$child))
	plus6.reps <- sum(cc[7:length(cc)])/sum(cc)

dd <- table(na.omit(women$child))
	plus6.women <- sum(dd[7:length(dd)])/sum(dd)

ee <- table(na.omit(men$child))
	plus6.men <- sum(ee[7:length(ee)])/sum(ee)
	
prop.six.or.greater <- cbind(plus6.all, plus6.dems, plus6.reps, plus6.women, plus6.men)
	
mean.female <- cbind(mean(na.omit(all$woman)), 
		mean(na.omit(dems$woman)),
		mean(na.omit(reps$woman)),
		mean(na.omit(women$woman)),
		mean(na.omit(men$woman))
	)
	
mean.rep <- cbind(mean(na.omit(all$republican)), 
		mean(na.omit(dems$republican)),
		mean(na.omit(reps$republican)),
		mean(na.omit(women$republican)),
		mean(na.omit(men$republican))
)


mean.white <- cbind(mean(na.omit(all$race == 1)), 
		mean(na.omit(dems$race == 1)),
		mean(na.omit(reps$race == 1)),
		mean(na.omit(women$race == 1)),
		mean(na.omit(men$race == 1))
	)

mean.yearb <- cbind(mean(na.omit(all$yearb)), 
		mean(na.omit(dems$yearb)),
		mean(na.omit(reps$yearb)),
		mean(na.omit(women$yearb)),
		mean(na.omit(men$yearb))
	)

no_judges <- cbind(nrow(all), nrow(dems), nrow(reps), nrow(women), nrow(men))

demographic_table <- rbind(mean.kids, mean.girls, prop.zero, prop.one,
	prop.two, prop.three, prop.four, prop.five, prop.six.or.greater, mean.female, mean.rep, mean.white, mean.yearb, no_judges)

colnames(demographic_table) <- c("All", "Democrats", "Republicans","Women", "Men")
rownames(demographic_table) <- c("Mean No. Children", "Mean No. Girls",
	"Proportion who have 0 children","1 children",
	"2 children", "3 children",
	"4 children", "5 Children", "6 Children or More", "Proportion Female", "Proportion Republican",
	"Proportion White", "Mean Year Born", "N")


kable(demographic_table, digits = 2, caption = "Table 2: Demographics of U.S. Courts of Appeals Judges Who Voted on Gender-Related Cases, 1996-2002") %>%
  kable_styling(full_width = F)

# I found that using kable was easier than xtable. The format isn't exact, but it was the best output I could come up with. 

```

```{r, echo = FALSE}
########################################################
## DATA ENTRY AND MANIPULATION (from replication code): Calculating the Weights (Number of Cases)
########################################################

no_cases <- matrix(data = NA, nrow = nrow(judge.means), ncol = 1)
for(i in 1:length(no_cases)){
	no_cases[i] <- nrow(women.cases[which(women.cases$name == judge.means$name[i]),])
	}

judge.means <- cbind(judge.means, no_cases)

## total number of cases we are working with

sum(judge.means$no_cases) 	# should be 2,674 reported in the paper

########################################################
## Calculating the Outcome Var
########################################################

no_liberalvote <- matrix(data = NA, nrow = nrow(judge.means), ncol = 1)
for(i in 1:length(no_liberalvote)){
	stuff <- women.cases[which(women.cases$name == judge.means$name[i]),]
	no_liberalvote[i] <- nrow(subset(stuff, vote == 2 | vote == 3))
	}

lib_vote_share <- no_liberalvote/no_cases

judge.means <- cbind(judge.means, no_liberalvote, lib_vote_share)
judge.means <- subset(judge.means, girls != "NaN")

########################################################
## Subsetting Data to Various Populations (for use later)
########################################################

## just women:
women.means <- subset(judge.means, woman == 1)

## just men:
men.means <- subset(judge.means, woman == 0)

## just republicans:
rep.means <- subset(judge.means, republican == 1)

## just democrats
dem.means <- subset(judge.means, republican == 0)

########################################################
## Calculating the Weights (Number of Cases)
########################################################

no_cases <- matrix(data = NA, nrow = nrow(judge.means), ncol = 1)
for(i in 1:length(no_cases)){
	no_cases[i] <- nrow(women.cases[which(women.cases$name == judge.means$name[i]),])
	}

judge.means <- cbind(judge.means, no_cases)

## total number of cases we are working with

sum(judge.means$no_cases)

########################################################
## Calculating the Outcome Var
########################################################

no_liberalvote <- matrix(data = NA, nrow = nrow(judge.means), ncol = 1)
for(i in 1:length(no_liberalvote)){
	stuff <- women.cases[which(women.cases$name == judge.means$name[i]),]
	no_liberalvote[i] <- nrow(subset(stuff, vote == 2 | vote == 3))
	}

lib_vote_share <- no_liberalvote/no_cases

judge.means <- cbind(judge.means, no_liberalvote, lib_vote_share)
judge.means <- subset(judge.means, girls != "NaN")

########################################################
## Subsetting Data to Various Populations (for use later)
########################################################

## just women:
women.means <- subset(judge.means, woman == 1)

## just men:
men.means <- subset(judge.means, woman == 0)

## just republicans:
rep.means <- subset(judge.means, republican == 1)

## just democrats
dem.means <- subset(judge.means, republican == 0)
```


```{r, echo = FALSE}
#######
#Table 3
#########

gg <- rbind (summary(judge.means$no_cases), summary(dem.means$no_cases), summary(rep.means$no_cases))

rownames(gg) <- c("All Judges", "Democrats", "Republicans")

kable(gg, caption = "Table 3: Distribution of the number of gender-related cases heard per judge, 1996-2002.", digits = 2) %>%
  kable_styling(full_width = F)

#Similar to table 2, I found it easier to use kable.
```


```{r, echo = FALSE, results="asis"}
########################################################
## Table 4: Core Results (WLS)
########################################################

################ Results for all judges

# judge.means <- subset(judge.means, child > 0)

#From replication code
my.out1 <- lm(lib_vote_share ~ as.factor(girls) + as.factor(child), 
	data = judge.means, weights = judge.means$no_cases)

my.out2 <- lm(lib_vote_share ~ I(girls>0) + as.factor(child), 
	data = judge.means, weights = judge.means$no_cases)

my.out3 <- lm(lib_vote_share ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race ==3), 
	data = judge.means, weights = judge.means$no_cases)

my.out4 <- lm(lib_vote_share ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race ==3) + as.factor(circuit.1), 
	data = judge.means, weights = judge.means$no_cases)

my.out5 <- lm(lib_vote_share ~ as.factor(girls) + as.factor(child), 
	data = subset(judge.means, child < 5 & child > 0), weights = judge.means$no_cases[which(judge.means$child > 0 & judge.means$child < 5)])

my.out6 <- lm(lib_vote_share ~ I(girls>0) + as.factor(child), 
	data = subset(judge.means, child < 5 & child > 0), weights = judge.means$no_cases[which(judge.means$child > 0 & judge.means$child < 5)])

my.out7 <- lm(lib_vote_share ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race ==3), 
	data = subset(judge.means, child < 5 & child > 0), weights = judge.means$no_cases[which(judge.means$child > 0 & judge.means$child < 5)])

my.out8 <- lm(lib_vote_share ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race ==3) + as.factor(circuit.1), 
	data = subset(judge.means, child < 5 & child > 0), weights = judge.means$no_cases[which(judge.means$child > 0 & judge.means$child < 5)])

stargazer(my.out1, my.out2, my.out3, my.out4, my.out5, my.out6, my.out7, my.out8,
	style = "ajps", type = "html", omit.stat = c("f","ser"), title = "Table 4: Weighted Least Squares Results, Gender-Related Cases Only",  digits = 2, omit = c("circuit"), covariate.labels = c("1 Girl","2 Girls","3 Girls","4 Girls","5 Girls","At Least 1 Girl",	
	"1 Child","2 Children","3 Children","4 Children","5 Children","6 Children","7 Children","8 Children",
	"9 Children","Republican","Age at Investiture","Catholic","Woman","African American","Hispanic","Constant"), dep.var.labels = "Outcome is proportion of feminist votes.  Models 1--4 are for all judges, while Models 5--8 are for judges with 1--4 children.  (No judge among those with 1--4 children had four girls.) All models include fixed effects for number of children and use weights based on the number of cases heard by each judge.")

## I could not figure out how to change the order of the rows, how to place the note about the different models at the bottom of the table, or how to divide up the chunks of columns with grouped subtitles. Things are a little bit out of order in this table. I found that changing the output/results type was key to successfully knitting.  
```




